
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 720
WINDOW_TITLE = "RayCasterPy"
WINDOW_BACKGROUND_COLOR = (0, 0, 0)

FPS_CAP = 100000000

TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = 10, 10
TILE_SIZE_S = TILE_WIDTH_S, TILE_HEIGHT_S = TILE_WIDTH - 0.5, TILE_HEIGHT - 0.5

PLAYER_SIZE = 3
PLAYER_SPEED = .05
